### ISSUE TITLE
INSTALL.md ?

### ISSUE THREAD

**Issue by imlonghao** [V-Paranoiaque/vca#2]
Nice project.
I am going to install vca to my server, but where is the INSTALL document?

**Comment by V-Paranoiaque** [comment]
Thank you.
Install documents and scripts are still in development.
I just published a quick install guide.
https://github.com/V-Paranoiaque/vca/blob/master/INSTALL.md

**Comment by imlonghao** [comment]
What is the password?
I tried admin:admin but failed.

**Comment by V-Paranoiaque** [comment]
It's admin:admin
I just published some fixes.
Update VCA and try again.
Do you have any error ?

**Comment by imlonghao** [comment]
来自 魅族 MX3

-------- 原始邮件 --------
发件人：Virgil <notifications@github.com>
时间：周二 1月13日 04:17
收件人：V-Paranoiaque/vca <vca@noreply.github.com>
抄送：imlonghao <imlonghao@fastmail.com>
主题：Re: [vca] INSTALL.md ? (#2)

**Comment by imlonghao** [comment]
Maybe I wrote a wrong Mysql information?
I didn't get any notice for the password after I filled the form and submit.
Just simply return the login form no matter what I enter to the form


来自 魅族 MX3

-------- 原始邮件 --------
发件人：Virgil <notifications@github.com>
时间：周二 1月13日 04:17
收件人：V-Paranoiaque/vca <vca@noreply.github.com>
抄送：imlonghao <imlonghao@fastmail.com>
主题：Re: [vca] INSTALL.md ? (#2)

**Comment by V-Paranoiaque** [comment]
Do you use a real domain or you modify your /etc/host ?
What is happening if you visit https://yourdomain/api.php ?

Try to add these lines in index.php and api.php juste after "<?php" :
ini_set('display_errors', 1);
error_reporting(E_ALL);

**Comment by imlonghao** [comment]
I was using a real domain during my test.
Sorry I can't test it at this moment, because I am in school......
I will test it in this Sunday and reply to this issue.


来自 魅族 MX3

-------- 原始邮件 --------
发件人：Virgil <notifications@github.com>
时间：周二 1月13日 19:49
收件人：V-Paranoiaque/vca <vca@noreply.github.com>
抄送：imlonghao <imlonghao@fastmail.com>
主题：Re: [vca] INSTALL.md ? (#2)

**Comment by V-Paranoiaque** [comment]
Can you give me some information :
- OS
- HTTP server and version
- PHP version

**Comment by imlonghao** [comment]
Debian7
Nginx 1.6.2
PHP 5.5

In user.sql, I notice that the username is Admin ?


来自 魅族 MX3

-------- 原始邮件 --------
发件人：Virgil <notifications@github.com>
时间：周二 1月13日 20:12
收件人：V-Paranoiaque/vca <vca@noreply.github.com>
抄送：imlonghao <imlonghao@fastmail.com>
主题：Re: [vca] INSTALL.md ? (#2)

**Comment by V-Paranoiaque** [comment]
Normally it's not case sensitive for the login.
I will try with the same configuration than you.

**Comment by V-Paranoiaque** [comment]
Check if you have : nginx php5-fpm mysql-server php5-mysql php5-mcrypt openssl

**Comment by V-Paranoiaque** [comment]
Is it ok for your problem ?

**Comment by imlonghao** [comment]
Very very sorry, I will have an exam in the last few day and I have no time to use computer............


Best wishes,
imlonghao

-------- 原始邮件 --------
发件人：Virgil <notifications@github.com>
时间：周四 1月22日 22:25
收件人：V-Paranoiaque/vca <vca@noreply.github.com>
抄送：imlonghao <imlonghao@esd.cc>
主题：Re: [vca] INSTALL.md ? (#2)

**Comment by V-Paranoiaque** [comment]
Is it ok for your problem ?

**Comment by andyalonzo** [comment]
Where i can generate the key and the port to add a server?
