### ISSUE TITLE
How to generate Security key.

### ISSUE THREAD

**Issue by andyalonzo** [V-Paranoiaque/vca#3]
I have installed the VCA Daemon and the VCA Web interface in the same server, but i can not find where generate the Security Key and the port to use the panel.
Can you put this in to the Wiki?

**Comment by V-Paranoiaque** [comment]
You can generate a key with sha256sum command.
Theses information are stored in /usr/share/vca/daemon/vca.cfg. Modify this file and restart vcadaemon.

**Comment by V-Paranoiaque** [comment]
Normally, if you have used my scripts, the security key is automatically generated.
The installation script ask to you the domain, just access to it with your web brother : https://yourdomain.
