### ISSUE TITLE
Reinstall

### ISSUE THREAD

**Issue by gamecraft45** [V-Paranoiaque/vca#5]
Reinstall button not work
PHP Fatal error:  Can't use method return value in write context in /usr/share/vca/www/templates/basic/popup_vpsreinstall.php on line 16, referer: http://xxxxxx.zz/vps/1

**Comment by V-Paranoiaque** [comment]
Thank you
Fixed in commit dfeb856c2ce87452268ee76cf6dd33e024dd9a4c

**Comment by gamecraft45** [comment]
Super it works :)
Can you tell me how it works Strong authentication?

**Comment by V-Paranoiaque** [comment]
I developed a mobile application. With the correct configuration it generates a Token every 30 seconds (by default). Both Tokens are compared and you are able to access to the panel.
https://github.com/V-Paranoiaque/OOTFY

**Comment by gamecraft45** [comment]
Sweet. Good job

**Comment by gamecraft45** [comment]
Small thing.
If you write smaller than 1GB Disk Space in MB, server always make 2.2GB
512MB not work but 0.5GB yes

**Comment by V-Paranoiaque** [comment]
I'm not able to reproduce your problem.
I did a test with 512MB and everything is OK.
