### ISSUE TITLE
Create new vps

### ISSUE THREAD

**Issue by geraldkacka** [V-Paranoiaque/vca#6]
Hello i have a problem when i click create new vps, not show anything, cpu load go to 100% used by php5-fpm, i have check my apache logs and nothing.

Iam use ubuntu 14.04

**Comment by V-Paranoiaque** [comment]
Hello,
Pull and run "service vcadaemon restart".
If /vz does not exist, run "ln -s /var/lib/vz /vz"

**Comment by geraldkacka** [comment]
thank you, solved :)
