### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by gamecraft45** [V-Paranoiaque/vca#7]
Hello
1) it is possible add some time restriction?
For example user paid one month, in administration I will set one month and after month user's vps will be stoped if he paid some months again (7 days before end his month, user will be notified in ssh and web administration about ending). VPS can't be started by user, after stop, user have for example 10 days for pay next month or his vps (data) will be deleted. This 10 days, user will still have FTP access to his VPS for download data.

2) FTP
Can you add FTP acces to web administration (It can be accessed by normal FTP client)?
Login it will be same as to web administration. After login user will see root.
In root will be folder named as his vps servers

3) Privilage
Can you add possibility to add more admins users (with custom names, and original admin can be disabled)

4) Can be OOTFY changed to Google Authenticator?

This is only a proposal, and if you had any idea to do it better I'll be happy :)

Thank you for read and I belive in some changes :)
I love yours web administration :)

I'm sorry for my terrible english

**Comment by V-Paranoiaque** [comment]
Hello,

Thank you for ideas but next time, please, create 4 issues.

1) Normally, you can use the API to do it.

2) Why not

3) You are already able to rename the original admin. I will add the possibility to add more admins. 
If you can't wait, just set "user_rank" to 1 in the DB for each new admin user.

4) Why not, if I have time.

Thank you for your support

**Comment by gamecraft45** [comment]
One big thanks
I thing, that yours web administration is better that SolusVM or another

**Comment by V-Paranoiaque** [comment]
Thx, before I used owp.

Normally the number 3 is ok.
https://github.com/V-Paranoiaque/vca/commit/37415a12d0a72e4918d188503e87048cdbdee971

**Comment by gamecraft45** [comment]
Me too
